### PR TITLE
[FABG-949] Add support for generating CRL with Revoke

### PR DESCRIPTION
**Pull request by samuelvenzi**
Currently in the SDK there's no GenCRL field in the msp.RevocationRequest. The msp.RevocationResponse, which has RevokedCerts and CRL fields, comes with an empty []byte for the CRL, so it's impossible to revoke a cert and then add de CRL to the config block, as required.

Signed-off-by: Samuel Venzi <samuel.venzi@me.com>

### CODE REVIEW

**Comment by kopaygorodsky** [comment]
I would add a few tests for it

**Comment by samuelvenzi** [comment]
> I would add a few tests for it

Well, the current unit test for revoke doesn't even account for the existing fields in the RevocationRequest struct: https://github.com/hyperledger/fabric-sdk-go/blob/master/pkg/msp/caclient_test.go#L410

**Review by alikic — CHANGES_REQUESTED** [review]
More changes are needed to implement this, for example response mapping at https://github.com/hyperledger/fabric-sdk-go/blob/92bda8e1d6bb9aea99890679acb354b7d9eb2012/pkg/client/msp/client.go#L436.

Integration test is needed to demonstrate receiving correct CRL when requested.

**Comment by vieiramanoel** [comment]
@alikic We've tested this fixed code in our production env and CRL are being generated at revoke although in tests CRL is allways a empty byte-array, is that something that i'm missing from environment? 
I'm running tests with `make unit-test`


```go
func TestRevoke(t *testing.T) {
	f := testFixture{}
	sdk := f.setup()
	defer f.close()

	ctxProvider := sdk.Context()

	// Get the Client.
	// Without WithOrg option, it uses default client organization.
	msp, err := New(ctxProvider)
	if err != nil {
		t.Fatalf("failed to create CA client: %s", err)
	}

	revokeResponse, err := msp.Revoke(&RevocationRequest{Name: "testuser", GenCRL: true})
	if err != nil {
		t.Fatalf("Revoke return error %s", err)
	}
        // revokeResponse.CRL is always [] at this point
}
```

**Comment by alikic** [comment]
@vieiramanoel Unit test uses mock CA server (https://github.com/hyperledger/fabric-sdk-go/blob/master/pkg/msp/test/mockmsp/mockfabriccaserver.go), which has only limited support for CA use cases. Adding more logic to the mock would allow for more complete testing, but we would have to replicate the real CA behaviour to approach full coverage. I would leave unit test as is.

Integration tests make calls to the actual CA. Looks like we don't have integration test for Revoke. Extending https://github.com/hyperledger/fabric-sdk-go/blob/92bda8e1d6bb9aea99890679acb354b7d9eb2012/test/integration/pkg/client/msp/enrollment_test.go#L57:6 with few lines at the end would do I think. Basically, just cal Revoke (with the new flag) and verify that the resulting CRL list contains the revoked cert.

**Comment by samuelvenzi** [comment]
@alikic Would this be okay inside `testRegisterEnrollWithCAInstance()`?

`revokeResponse, err := mspClient.Revoke(&msp.RevocationRequest{Name: username, GenCRL: true})
	if err != nil {
		t.Fatalf("Revoke return error %s", err)
	}
	if revokeResponse.CRL == nil {
		t.Fatalf("Couldn't retrieve CRL")
	}`

**Comment by samuelvenzi** [comment]
@alikic Would this be okay inside `testRegisterEnrollWithCAInstance()`?

```golang
revokeResponse, err := mspClient.Revoke(&msp.RevocationRequest{Name: username, GenCRL: true})
if err != nil {
	t.Fatalf("Revoke return error %s", err)
}
if revokeResponse.CRL == nil {
	t.Fatalf("Couldn't retrieve CRL")
}
```

**Comment by alikic** [comment]
@samuelvenzi Yes, that looks fine. You also need to verify that the returned CRL includes the cert you wanted to revoke.

**Comment by samuelvenzi** [comment]
@alikic just added the integration test for revoke by extending the `testRegisterEnrollWithCAInstance()` as requested. Could review it, please?

**Review by alikic — APPROVED** [review]

**Pull request merged**
