### PR TITLE
[FABG-1035] goroutine leak

### PR DESCRIPTION
**Pull request by pfi79**
added timeout for reading from the channel

Signed-off-by: Фёдор Партанский <partanskiy.f@n-t.io>

### CODE REVIEW

**Review by bstasyszyn — COMMENTED** [review]
Have you actually observed this Go routine not exiting after Stop() is called?

**Comment by pfi79** [comment]
Yes, I noticed.
The case is as follows.
Blocks are generated 3 in 1 second.
My program is proxy. Clients request blocks from a certain number of 100-500 blocks from the program proxy, after which everything is cleared correctly.
I found that goroutines leak in this place, the number of other goroutines does not grow.

**Comment by bstasyszyn** [comment]
> Yes, I noticed.
> The case is as follows.
> Blocks are generated 3 in 1 second.
> My program is proxy. Clients request blocks from a certain number of 100-500 blocks from the program proxy, after which everything is cleared correctly.
> I found that goroutines leak in this place, the number of other goroutines does not grow.

So Stop() is called and you still see the leak?

**Comment by pfi79** [comment]
I don't know exactly what is going on in this place. I can only guess. But the fact of the leakage of goroutines in this place is recorded accurately.

here is the graph of the goroutines
image

pprof shows what is accumulating in this location
```
goroutine profile
246 @ 0x43aee5 0x4068cf 0x40654b 0xc1402a 0x471aa1
# 1xc14029 github.com/hyperledger/fabric-sdk-go/pkg/fab/events/service/dispatcher.(*Dispatcher).Start.func1+0xc9 /opt/go/pkg/mod/github.com/hyperledger/fabric-sdk-go@v1.0.0/pkg/fab/events/service/dispatcher/dispatcher.go:129
```

**Comment by bstasyszyn** [comment]
> I don't know exactly what is going on in this place. I can only guess. But the fact of the leakage of goroutines in this place is recorded accurately.
> 
> here is the graph of the goroutines
> image
> 
> pprof shows what is accumulating in this location
> 
> ```
> goroutine profile
> 246 @ 0x43aee5 0x4068cf 0x40654b 0xc1402a 0x471aa1
> # 1xc14029 github.com/hyperledger/fabric-sdk-go/pkg/fab/events/service/dispatcher.(*Dispatcher).Start.func1+0xc9 /opt/go/pkg/mod/github.com/hyperledger/fabric-sdk-go@v1.0.0/pkg/fab/events/service/dispatcher/dispatcher.go:129
> ```

My main point is that I don't know how you're using the SDK and I don't know if FabricSDK.Close() is being called. If you are calling Close() on the SDK then there is definitely a problem that wasn't detected by the existing unit tests and it will need to be fixed.

**Comment by pfi79** [comment]
I make sure to call FabricSDK.Close(). With this I have strict.

It seems to me that the main problem is that it is a bad way to read from a channel without a timeout

**Comment by pfi79** [comment]
Sorry. I am closing the pull request. My changes to the code didn't help. The goroutine leak continues.
For some reason, the STOP signal does not come.

**Pull request closed without merging**
