### PR TITLE
Added support for fromBlock when generating eventservice cache keys

### PR DESCRIPTION
**Pull request by jimthematrix**
The current cache key only takes into account the channel ID, which means if I have a different `fromBlock` number, or chaincode Id with a subsequent `RegisterBlockEvent()` call, it would not take effect because the previous event service will be returned from the cache lookup.

### CODE REVIEW

**Comment by kopaygorodsky** [comment]
Hey @jimthematrix,  are you going to continue working on this PR (fix tests, code coverage)? I've stumbled on this issue as well and would like to help if this PR is stale.

**Comment by jimthematrix** [comment]
@kopaygorodsky thanks for offering to help, I haven't been able to get back to this one. if you are able to spare some cycles on the tests that'd be much appreciated!

**Review by bstasyszyn — APPROVED** [review]

**Comment by kopaygorodsky** [comment]
@bstasyszyn this PR introduced an issue that we are facing right now. Over time the cache of event services grows because `fromBlock` became part of the cacheKey and each reconnect with a higher `fromBlock` param produces a new service that will never be purged. I propose to add the Close() method to the event service interface to give some control to a client. 
WDYT?

**Comment by kopaygorodsky** [comment]
@bstasyszyn hey, this PR raised a problem related to the lazycache component. Each event client with a different starting block number is a new entry in the cache. It has some idling timeout and then calls finalizer which closes the connection and resets Ref to nil, but the key in the cache stays. One of my environments has very often reconnections with increasing block number param each time so in a week it resulted in 200Mb of keys in the cache. 
I see three possible solutions to this problem: 

- IOC of the `context.ChannelProvider` in the constructor of the event client. It gives the user ability to create channel context and close it manually. On `CloseContext` all cached are cleaned. 
- By fixing the `reset mode` of the Reference. Put the link of the `Cache` into the Reference so it can clean up its key in the `handleExpiration` method.
- Add the `DeleteOnlyKey` method to the cache, so it just deletes the key without calling `close()`. In that way a callback with that method can be put into a custom finalizer.

**Comment by kopaygorodsky** [comment]
@bstasyszyn

**Pull request merged**
