### PR TITLE
[FABG 998]Integration tests

### PR DESCRIPTION
**Pull request by huangjiehua**
Integration tests include:  package cc, install cc, get installed cc package, query installed cc, approve cc, query approve cc, check commit readiness, commit cc, query committed cc

Signed-off-by: huangjiehua <huangjiehua@aisino.com>

### CODE REVIEW

**Comment by huangjiehua** [comment]
hi @bstasyszyn. There are two Fabric-SDK-GO(Integeration Test), and one is  successful, but the other is canceled. The log turned out to be "Build not found" which is canceled. I would appreciate your help and advice as to what I should do next.

**Comment by bstasyszyn** [comment]
> hi @bstasyszyn. There are two Fabric-SDK-GO(Integeration Test), and one is successful, but the other is canceled. The log turned out to be "Build not found" which is canceled. I would appreciate your help and advice as to what I should do next.

Not sure where this build came from. @troyronda do you know?

**Review by bstasyszyn — APPROVED** [review]

**Comment by troyronda** [comment]
@bstasyszyn Not sure why this extra test run showed up.

**Comment by troyronda** [comment]
@huangjiehua looks like this PR is ready. would you mind adding a DCO sign-off commit formatted with with your full name.

`Signed-off-by: Legal Name <email-address>`.

**Comment by huangjiehua** [comment]
> @huangjiehua looks like this PR is ready. would you mind adding/amending a DCO sign-off commit formatted with your full name.
> 
> `Signed-off-by: Legal Name <email-address>`.
> 
> Thanks very much and thanks again for your contribution.

Thank you for the review. After DCO sign-off, do I need to make a new PR?

**Comment by troyronda** [comment]
@huangjiehua I noticed that your sign-off in your commit is `huangjiehua <huangjiehua@aisino.com>`. I was hoping you could include & format your full name in the commit sign-off.

Yes `git commit --amend` works.

**Review by troyronda — APPROVED** [review]

**Comment by troyronda** [comment]
@bstasyszyn @huangjiehua Looks like the merge commit has some linter errors that were missed in the PR linter check.

https://dev.azure.com/Hyperledger/Fabric-SDK-Go/_build/results?buildId=18949&view=logs&jobId=1c778e8e-596b-5a0a-22c2-460364725d7c&j=1c778e8e-596b-5a0a-22c2-460364725d7c&t=e316d21a-7c0e-5fb0-c3c7-045475225585

**Comment by troyronda** [comment]
@bstasyszyn @huangjiehua Merge integration tests timed out after an hour, but looked like they were going to pass.

**Comment by huangjiehua** [comment]
@troyronda , I fouond the problems.  Do I need to fix this in the new PR?

**Comment by troyronda** [comment]
@huangjiehua I am not sure why the linter didn't run on this file in the original PR.

Your changes are merged, so a new PR with the fixes would be great. Thanks again!

**Pull request merged**
